@baseUrl = {{$dotenv API_URL}}

### * * Génération d'Uuid
GET {{baseUrl}}/genshin/generate-uuid HTTP/1.1
Content-Type: application/json

### * Récupération d'une données en BDD

GET {{baseUrl}}/genshin/getData HTTP/1.1
content-type: application/json

{
    "uuid": "a258572f-f67c-49d8-a953-5616a2431f32",
    "data_type": "test"
}

### * Sauvegarde d'une données en BDD - 1

POST {{baseUrl}}/genshin/saveData HTTP/1.1
content-type: application/json

{
    "uuid": "a258572f-f67c-49d8-a953-5616a2431f32",
    "data_type": "options",
    "data_string": "On remplace"
}

### * Sauvegarde d'une données en BDD - 2

POST {{baseUrl}}/genshin/saveData HTTP/1.1
content-type: application/json

{
    "uuid": "a258572f-f67c-49d8-a953-5616a2431f32",
    "data_type": "test",
    "data_string": "ecalpmer nO"
}

### * Connexion avec son uuid

GET {{baseUrl}}/genshin/login HTTP/1.1
content-type: application/json

{
    "uuid": "a258572f-f67c-49d8-a953-5616a2431f32"
}

### * Connexion avec son uuid

POST {{baseUrl}}/genshin/getData HTTP/1.1
content-type: application/json

{
    "uuid": "9a1c9cd7-dbcc-4cc1-8896-02359bae877e",
    "data_type": "genshinCharactersData"
}